### ISSUE TITLE
Can't find executable path

### ISSUE THREAD

**Issue by MyJirapat** [jontewks/heroku-buildpack-puppeteer-firefox#5]
When I deploy this code on Heroku the error shows that they can't find an executable firefox path

const puppeteer = require('puppeteer')
//const nodeCron = require("node-cron")
const sch = require("node-schedule")
//const ora = require("ora");
//const chalk = require("chalk");
const fs = require("fs/promises")
const mongo = require("mongodb").MongoClient

// Connect to MongoDB Database
const url = "";let db, TL
mongo.connect(
    url,
    {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    },
    (err, client) => {
      if (err) {
        console.error(err)
        return
      }
      db = client.db("TL")
      TL = db.collection("TL")

async function VeederRoot() {
   try {
       const date = Date.now();
       const browser = await puppeteer.launch({
        headless: true,
        //slowMo: 50,
        product: 'firefox',
        ignoreHTTPSErrors: true,
        args: ['--ignore-certificate-errors', '--ignore-certificate-errors-spki-list', '--enable-features=NetworkService', '--no-sandbox',
        '--disable-extensions','--use-gl=egl', '--disable-setuid-sandbox'],
        ignoreDefaultArgs: ["--disable-extensions"],
        //executablePath: 'C:/Program Files/Mozilla Firefox/firefox.exe',
        FIREFOX_BIN: '/app/vendor/firefox/firefox',
        //executablePath: '/app/vendor/firefox/firefox'
        //executablePath: '/app/vendor/firefox/firefox'
        //Selenium:WebDriver:Firefox:Binary.path = "/app/vendor/firefox/firefox"
       })
       const page = await browser.newPage()
       console.time()
       await page.goto('https://essotheone.thaiddns.com:4433/#LogIn')
       console.time()
       await page.type('#gwt-debug-userNameTextBox', "");
       console.time()
       await page.type('#gwt-debug-userPasswordTextBox', "");
       await Promise.all([
        page.click("#gwt-debug-signInButton"),
        console.time(),
       // page.click("#gwt-debug-tankItem4 > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2) > a:nth-child(2)"),
        page.waitForNavigation(),
        console.time()
    ]);

    await page.waitForSelector('#gwt-debug-tankItem1 > table:nth-child(1)');
        // Get data from Veeder-root web page      
        let data = await page.evaluate(() => {
          console.time()
           const items = Array.from(document.querySelectorAll('.TankOverviewTableItem'))
           console.time()
           let results = [];
           let allTank = [];
           let ts = Date.now();
             const dat = new Date(ts)
             console.time()
             const day = dat.getDate()
             console.time()
             const month = dat.getMonth() +1
             console.time()
             const year = dat.getFullYear()
             console.time()
            // const time = dat.getTi
             const date = `${day}/${month}/${year}`
           items.forEach((item) => {   
            console.time()
                 const select = item.querySelectorAll("#_paramName.tank_item_div_height");
                 console.time()
                 const TankName = item.querySelector('.TankLabel');
                 console.time()
                 console.time(TankName)
                 const T = TankName;
                 //const D = fulldate;
                 const V = select[0];
                 console.time()
                 console.time()
                 const U = select[1];
                 console.time()
                 console.time()
                 const W = select[2];
                 console.time()
                 console.time()
                 const F = select[3];
                 console.time()
                 console.time()
                 allTank.push({ TankName: T.innerText,
                    Volume:V.innerText, 
                    
                    Ullage: U.innerText,
                    Waterheight: W.innerText,
                    Fuelheight: F.innerText
                  })
                   //url: item.getAttribute('data-url'),
                   //Tank: item.querySelector('.TankLabel').innerText,
                   //Volume: item.querySelector('.tank_item_div_height').textContent,
                   //Ullage: item.querySelector('#gwt-debug-tankItem1 > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2) > div:nth-child(1) > div:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > div:nth-child(1)').textContent
               });
             results.push({
                    date,
                    //Time: D.innerText, 
                    Tank: allTank,  
                });
                //console.time(data)
               return results
           });
            console.log(data)
            console.time()
            TL.insertMany(data)
            await browser.close()
   } catch (error) {
       console.error(error)
   }
}
sch.scheduleJob("0 8 * * *",VeederRoot);
//sch.scheduleJob("*/30 * * * * *",VeederRoot);
VeederRoot()
//sch.cancelJob()
})

**Comment by jontewks** [comment]
Just ran the test with a minimal example of just going to a page and verifying its working and see that I'm not experiencing this same issue.
![image](https://user-images.githubusercontent.com/3970573/187708993-13951325-83a9-42cd-b7cf-ddec436779f0.png)

Do you have the environment variable set on heroku listed in the readme so it installs firefox? Have you tried on the latest heroku stack, with the latest version of puppeteer?

**Comment by MyJirapat** [comment]
![image](https://user-images.githubusercontent.com/74519762/187867245-3edc7dba-dabd-453c-91c9-1d84ab630fd2.png)
Yes, I have tried on the latest stack but it shows like this.

**Comment by MyJirapat** [comment]
![image](https://user-images.githubusercontent.com/74519762/187868278-6f3806d9-7704-448c-8ebb-2c9808fd25f8.png)

**Comment by jontewks** [comment]
@MyJirapat thanks for those screenshots. You'll see in the last one it is asking for you to set the `PUPPETEER_PRODUCT=firefox` environment variable so it will install the correct browser to use. Please set that environment variable on heroku.
