### ISSUE TITLE
Problem with puppeteer V19 

### ISSUE THREAD

**Issue by nairihar** [jontewks/heroku-buildpack-puppeteer-firefox#7]
Please see the breaking changes: https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer/CHANGELOG.md#1900-2022-10-14

**Comment by jontewks** [comment]
Please clear your build cache as mentioned in the readme if you’re experiencing cache issues on Heroku.

**Comment by nairihar** [comment]
Dear @jontewks it wasn't a cache problem. Puppeteer changed the download location of the executable (browser).

First Heroku builds and then it compresses the files so they will be used when the container will start.
At that time Heroku misses the executable file.

So we need to do something like this in `postbuild`:

```
mkdir ./.cache

mv /app/.cache/puppeteer ./.cache
```

**Comment by nairihar** [comment]
You will get this kind of error even if you try to clean Heroku's build cache.

<img width="840" alt="Screenshot 2023-04-03 at 18 21 16" src="https://user-images.githubusercontent.com/15065065/229554656-06150841-667a-46c7-8ce2-53a051394e8c.png">

**Comment by jontewks** [comment]
The buildpack doesn't make any decisions where the cache is, but if you've upgraded from the older puppeteer to the newer one, you'll run into cache issues. It's working on my minimal example and is also the same setup as the non firefox version, so it appears as if you've got a cache issue on heroku. Some folks had issues even after clearing the cache as it appeared as if Heroku kept something around still, so try creating a new heroku app with your same code if the issue persists.

**Comment by nairihar** [comment]
I wrote an article about this issue, I hope this will be helpful to others :)

https://nairihar.medium.com/how-to-use-puppeteer-in-heroku-9de2ab31bc11

**Comment by jontewks** [comment]
Thanks @nairihar that looks quite well written.

Did you try it with a new app as well? My minimal test is working without that change.
